/**
 * Create a public function that handle request to the Bitcoin API, this code is generated by Github Copilot
 */
exports.getBitcoinPrice = function(callback) {
    //Create a bitcoin API that will call bitcoin price from Coinbase
    let url = 'https://api.coinbase.com/v2/prices/spot?currency=USD';
    fetch(url).then(function (response) {
        return response.json();
    }).then(function (data) {
        callback(data.data.amount);
    });
}